<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2024/03/11 16:11:31

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=advanced_form',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
